site_name: Conocimiento Abierto
site_description: Blog personal de Francisco Puga
site_url: https://fpuga.github.io/conocimientoabierto
site_author: Francisco Puga
copyright: Copyright (C) 2007-2024 Francisco Puga. Bajo licencia CC-BY 4.0.

theme:
  name: material
  language: es
  custom_dir: overrides
  palette:
      scheme: conocimientoabierto
  features:
      - navigation.indexes
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.top
      - navigation.instant
      - navigation.instant.progress
      - navigation.tracking
      - header.autohide
      - toc.follow
      - content.code.copy


extra_css:
    - extra/extra.css
extra_javascript:
    - extra/extra.js

exclude_docs: |
    drafts/            # A "drafts" directory anywhere.

# strict: true

validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - "General"
        - "Ibrahima Niang"
        - "Palestina"
        - "Sin categoría"
        - "activismo"
        - "blog action day"
        - "bombas de racimo"
        - "ciberactivismo"
        - "comunicacion"
        - "comunicaciong"
        - "conocimiento abierto"
        - "cooperacion"
        - "cultura"
        - "curiosidades"
        - "d-link dsl-200"
        - "deuda externa"
        - "drivers"
        - "ecologia"
        - "economia"
        - "epd"
        - "esf"
        - "genetica"
        - "globalizacion"
        - "ideologia"
        - "intimo"
        - "itrust wb-1200p"
        - "linux"
        - "literatura"
        - "migracion"
        - "mundodesigual07"
        - "politica"
        - "portatil"
        - "primates"
        - "receta"
        - "recomendacion"
        - "relato"
        - "scripting"
        - "sexismo"
        - "shell"
        - "tercer sector"
        - "voluntariado"
        - "web 2.0"
        - "webcam"
      pagination_per_page: 5
  - tags:
      enabled: true
      tags: true
      tags_file: tags.md
      # tags_file: blog/tags.md
      tags_allowed:
        - "2011"
        - "Asimov"
        - "Crockford"
        - "Dickens"
        - "Escoger IDE web"
        - "Escuela de Robinsones"
        - "Harper Lee"
        - "IDE"
        - "Ken Robinson"
        - "Kent Beck"
        - "La era del diamante"
        - "Los Soprano"
        - "Matar a un ruiseñor"
        - "Nada Es Gratis"
        - "Neal Stephenson"
        - "Pat Cadigan"
        - "Robert A. Heinlein"
        - "SOPA"
        - "Verne"
        - "activismo"
        - "addyosmani"
        - "alojamiento"
        - "android"
        - "análisis de redes"
        - "análisis estático de código"
        - "apache"
        - "arcadi oliveres"
        - "arquitectura"
        - "asuntos militares"
        - "atom"
        - "audio"
        - "backbonejs"
        - "backup"
        - "base de datos"
        - "bash"
        - "blogroll"
        - "bloguzz"
        - "bolsa-caca"
        - "bootstrap"
        - "browser"
        - "buenas prácticas"
        - "bug"
        - "cad"
        - "cartolab"
        - "censura"
        - "charlas"
        - "ciberactivismo"
        - "ciberpunk"
        - "cienc"
        - "ciencia ficción"
        - "cifrado"
        - "cifrar"
        - "cinco erres"
        - "clickactivismo"
        - "coding style"
        - "como"
        - "comparativa"
        - "comprar portátil"
        - "comprar portátil 2019"
        - "comunidad"
        - "concierto"
        - "conferencia"
        - "consenso"
        - "cooperacion"
        - "copyright"
        - "correo-e"
        - "crisis"
        - "css"
        - "dan pink"
        - "decrecimiento"
        - "democracia económica"
        - "dependencies"
        - "deploy"
        - "derecho al voto"
        - "desarrollo"
        - "desarrollo humano"
        - "desarrollo software"
        - "desarrollo sofware"
        - "desarrollo web"
        - "diseño web"
        - "dispositivos móviles"
        - "diy"
        - "django"
        - "docx"
        - "domino público"
        - "dropbox"
        - "ducksboard"
        - "duncan green"
        - "eclipse"
        - "economia"
        - "educación"
        - "el padrino"
        - "emacs"
        - "empresa"
        - "empresa ética"
        - "enlaces"
        - "entorno de desarrollo"
        - "entrada corta"
        - "estadísticas"
        - "estilo de código"
        - "excel"
        - "expressjs"
        - "fabbing"
        - "facebook"
        - "feed"
        - "feedburner"
        - "file"
        - "filosofia"
        - "financiación"
        - "firefox"
        - "flask"
        - "foss4g"
        - "fundraising"
        - "futuro"
        - "geoprocesos"
        - "girona"
        - "gis"
        - "git"
        - "github"
        - "gitlab"
        - "guerra civil española"
        - "guerras postmodernas"
        - "gvfs"
        - "gvfsd-trash"
        - "gvsig"
        - "hardware"
        - "herramientas"
        - "hosting"
        - "how to"
        - "html"
        - "hyperion"
        - "i18n"
        - "icarto"
        - "identidad corporativa"
        - "identidad digital"
        - "impresora 3D"
        - "indarki"
        - "ine"
        - "infraestructura"
        - "isf"
        - "java"
        - "javascript"
        - "jeffrey sachs"
        - "jennifer gobierno"
        - "karaoke"
        - "khan academy"
        - "laborate"
        - "legislación"
        - "libreoffice"
        - "libro"
        - "libros"
        - "licencias"
        - "liferea"
        - "linked data"
        - "linux"
        - "lopd"
        - "mafia"
        - "maker"
        - "mapas"
        - "mario puzo"
        - "marketing"
        - "max barry"
        - "medio ambiente"
        - "meta"
        - "mitos"
        - "mobilidad"
        - "mod_python"
        - "modelo de datos"
        - "modelos de negocio"
        - "monetization"
        - "mooc"
        - "motivacion"
        - "mvc"
        - "nodejs"
        - "odiseus"
        - "ofimática"
        - "ong"
        - "open data"
        - "opencadtools"
        - "openlayers"
        - "opinión"
        - "oriente medio"
        - "patch"
        - "patentes"
        - "patrones"
        - "paypal"
        - "pcr"
        - "permalinks"
        - "portátil"
        - "poss"
        - "poss-gl"
        - "postgis"
        - "postgresql"
        - "postresql"
        - "productividad"
        - "programación"
        - "propiedad intelectual"
        - "punk world"
        - "python"
        - "público vs privado"
        - "rdf"
        - "ready player one"
        - "receta"
        - "recomendacion"
        - "recomendaciones"
        - "refactoring"
        - "rendimiento"
        - "rsgs"
        - "rss"
        - "ruby"
        - "salud"
        - "sanidad"
        - "scolab"
        - "script"
        - "seguridad"
        - "seo"
        - "serie"
        - "siglibre2011"
        - "sincronizar"
        - "siria"
        - "sistema operativo"
        - "sistemas"
        - "skype"
        - "soberanía digital"
        - "software"
        - "software libre"
        - "south"
        - "space opera"
        - "spam"
        - "sáhara"
        - "teatro"
        - "teclado"
        - "teledetección"
        - "televisión"
        - "tercer sector"
        - "torrent"
        - "traducción"
        - "transmission"
        - "tren"
        - "tropas del espacio"
        - "tutorial"
        - "ubuntu"
        - "videos"
        - "vigoblog"
        - "violencia"
        - "virtualbox"
        - "vivienda"
        - "vídeo"
        - "web"
        - "web semántica"
        - "wikileaks"
        - "william easterly"
        - "windows"
        - "word"
        - "wordpress"
        - "workshop"
        - "xls"
        - "xlsx"
        - "yahoo pipes"
        - "young adult"
        - "youtube"
  - privacy:
      enabled: !ENV [CI, false]

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      name: fpuga on GitHub
      link: https://github.com/fpuga
    - icon: fontawesome/brands/twitter
      name: fpuga on X
      link: https://x.com/fpuga
    - icon: fontawesome/brands/stack-overflow
      name: fpuga on StackOverflow
      link: https://stackoverflow.com/users/930271/francisco-puga
      

markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Proyectos: proyectos/
  - Tags: tags.md
  - Blog:
     - blog/index.md
     # - blog/tags.md
